name: example
description: Example configuration
version: 1.0.0
templates:
  - default
rules:
  example-rule:
    description: Example rule for demonstration purposes
    globs:
      - src/**/*.ts
      - src/**/*.tsx
    alwaysApply: true
    content:
      Main Points:
        - This is an example rule
        - It demonstrates the basic structure
        - Use this as a template for your own rules
      Examples:
        - |-
          ```typescript
          // Example code
          function example() {
            console.log("Hello, world!");
          }
          ```
