name: organization-config
level: organization

# Base rules that apply to all projects and teams
rules:
  code-formatting:
    description: "Common code formatting standards"
    globs: ["**/*.{ts,js,tsx,jsx}"]
    alwaysApply: true
    content:
      indentation: 2
      max_line_length: 100
      quote_style: "single"
      trailing_comma: true

  naming-conventions:
    description: "Standard naming conventions for variables and functions"
    globs: ["src/**/*.{ts,js}"]
    alwaysApply: true
    content:
      variables: "camelCase"
      functions: "camelCase"
      classes: "PascalCase"
      interfaces: "PascalCase"
      constants: "UPPER_CASE"

  git-practices:
    description: "Standard Git workflow practices"
    globs: ["**/README.md", "**/*.md"]
    alwaysApply: false
    content:
      commit_message_format: "conventional"
      branch_naming: "feature/{ticket}-{description}"
      pr_template: |
        ## Description
        
        Please include a summary of the change and which issue it addresses.
        
        ## Type of change
        
        - [ ] Bug fix
        - [ ] New feature
        - [ ] Breaking change
        - [ ] Documentation update

# Standard templates available to all projects
templates:
  - name: "rule-template"
    description: "Standard template for generating rule MDC files"
    path: "../templates/rule-template.hbs"

  - name: "readme-template"
    description: "Standard template for generating README files"
    path: "../templates/readme-template.hbs"

# Default values for all projects
defaults:
  repository:
    structure:
      src: "Source code"
      tests: "Test files"
      docs: "Documentation"
  
  documentation:
    required_sections:
      - "Overview"
      - "Installation"
      - "Usage"
      - "API"
      - "Contributing"
      - "License" 